import Link from "next/link";

export default function MarketingHome() {
  return (
    <main className="mx-auto flex min-h-screen max-w-3xl flex-col items-center justify-center gap-6 px-6 text-center">
      <h1 className="text-4xl font-bold tracking-tight text-brand-dark">
        Training built for how ultimate actually stresses your body.
      </h1>
      <p className="max-w-xl text-lg text-slate-600">
        Season-long strength &amp; conditioning programs, generated by AI from one
        coach&apos;s real philosophy and exercise library — individualized to your
        schedule, your equipment, and your injury history, and rebuilt as your
        season changes.
      </p>
      <div className="flex gap-3">
        <Link
          href="/app/intake"
          className="rounded-md bg-brand px-6 py-3 font-medium text-white hover:bg-blue-700"
        >
          Start your intake
        </Link>
        <Link
          href="/login"
          className="rounded-md border border-slate-300 px-6 py-3 font-medium text-slate-700 hover:border-brand hover:text-brand"
        >
          Log in
        </Link>
      </div>
    </main>
  );
}
