import Link from "next/link";

/**
 * DRAFT — placeholder legal content, not reviewed by an attorney. Fill in
 * [APP NAME], [COMPANY NAME/ENTITY], [JURISDICTION], and [CONTACT EMAIL]
 * once those are decided, and have a lawyer review this before it governs
 * real paying users. It exists now so the app has *something* real at
 * /terms rather than nothing, and so it can be linked from signup once
 * that flow is ready to require acceptance.
 */
export default function TermsPage() {
  return (
    <main className="mx-auto max-w-2xl px-6 py-16">
      <Link href="/login" className="text-sm text-brand underline">
        ← Back
      </Link>

      <h1 className="mt-4 text-2xl font-bold text-brand-dark">Terms of Service</h1>
      <p className="mt-1 text-sm text-slate-500">Draft — last updated [DATE]. Not final; pending legal review.</p>

      <div className="prose prose-slate mt-8 max-w-none space-y-6 text-sm leading-6 text-slate-700">
        <section>
          <h2 className="text-base font-semibold text-brand-dark">1. Acceptance of terms</h2>
          <p>
            By creating an account or using [APP NAME] (the &ldquo;Service&rdquo;), operated by [COMPANY NAME]
            (&ldquo;we,&rdquo; &ldquo;us&rdquo;), you agree to these Terms of Service. If you don&apos;t agree,
            don&apos;t use the Service.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-brand-dark">2. What the Service is</h2>
          <p>
            The Service generates strength and conditioning training programs for ultimate frisbee players using
            an AI system, reviewed and approved by a human coach before being delivered to you. Programs are based
            on information you provide (intake answers, logged workouts, injury history) and are not a substitute
            for individualized medical or professional athletic training advice.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-brand-dark">3. Not medical advice — health &amp; safety</h2>
          <p>
            <strong>The Service is not a medical service, and nothing in it constitutes medical advice, diagnosis,
            or treatment.</strong> Consult a physician before beginning any new exercise program, especially if you
            have a pre-existing injury, medical condition, or are unsure whether an activity is appropriate for
            you. You are solely responsible for stopping any exercise that causes pain and for seeking appropriate
            medical care.
          </p>
          <p>
            Exercise carries an inherent risk of injury. By using the Service, you voluntarily assume all risks
            associated with performing the programs it generates, including but not limited to injury, disability,
            or death. To the fullest extent permitted by law, [COMPANY NAME] is not liable for any injury arising
            from your use of a program generated by the Service.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-brand-dark">4. Accounts &amp; eligibility</h2>
          <p>
            You must provide accurate information, including accurate injury and health history — the programs
            you receive are only as safe as the information you give us. You must be at least [13/16/18 — set
            per jurisdiction] years old to create an account; if you are a minor where required, a
            parent/guardian must consent on your behalf. You are responsible for keeping your login credentials
            confidential and for all activity under your account.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-brand-dark">5. Subscriptions &amp; payment</h2>
          <p>
            Some features of the Service require a paid subscription, billed on a recurring basis (e.g. monthly)
            until cancelled. Prices, billing cadence, and cancellation terms will be presented at sign-up and are
            incorporated into these Terms by reference. [Add refund policy, trial terms, and payment processor
            (e.g. Stripe) details once payments are implemented.]
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-brand-dark">6. Your content</h2>
          <p>
            You retain ownership of the information you provide (intake answers, logged workouts, notes). You
            grant us a license to use it to operate the Service — including generating your programs and, if you
            or your coach opt in, using an anonymized/de-identified version of an approved program as a reference
            example to help generate other athletes&apos; programs.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-brand-dark">7. Termination</h2>
          <p>
            You may stop using the Service and request account deletion at any time. We may suspend or terminate
            an account that violates these Terms or misuses the Service (including attempting to abuse or overload
            the AI generation features).
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-brand-dark">8. Disclaimer of warranties</h2>
          <p>
            The Service is provided &ldquo;as is&rdquo; without warranties of any kind, express or implied,
            including fitness for a particular purpose. We do not guarantee that AI-generated content will be
            error-free or achieve any particular athletic outcome.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-brand-dark">9. Limitation of liability</h2>
          <p>
            To the fullest extent permitted by law, [COMPANY NAME] will not be liable for any indirect,
            incidental, or consequential damages arising from your use of the Service, and our total liability
            for any claim will not exceed the amount you paid us in the 12 months before the claim arose.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-brand-dark">10. Changes to these terms</h2>
          <p>
            We may update these Terms from time to time. We&apos;ll notify you of material changes (e.g. by email
            or in-app notice) before they take effect.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-brand-dark">11. Governing law &amp; contact</h2>
          <p>
            These Terms are governed by the laws of [JURISDICTION]. Questions? Contact us at [CONTACT EMAIL].
          </p>
        </section>
      </div>
    </main>
  );
}
