import Link from "next/link";

/**
 * Real (filled-in) Terms of Service for the beta — no lawyer has reviewed
 * this. It's a reasonable, standard-shape ToS for a small free beta run by
 * an individual, not a substitute for legal review. Revisit this (ideally
 * with an actual lawyer) before charging money, before incorporating a
 * business entity, or before this involves users outside a small beta
 * group you know personally.
 */
export default function TermsPage() {
  return (
    <main className="mx-auto max-w-2xl px-6 py-16">
      <Link href="/login" className="text-sm text-brand underline">
        ← Back
      </Link>

      <h1 className="mt-4 text-2xl font-bold text-brand-dark">Terms of Service</h1>
      <p className="mt-1 text-sm text-slate-500">Last updated September 23, 2026.</p>

      <div className="prose prose-slate mt-8 max-w-none space-y-6 text-sm leading-6 text-slate-700">
        <section>
          <h2 className="text-base font-semibold text-brand-dark">1. Acceptance of terms</h2>
          <p>
            By creating an account or using Ultimate Training (the &ldquo;Service&rdquo;), operated by Quinn Ledak
            (&ldquo;we,&rdquo; &ldquo;us&rdquo;), you agree to these Terms of Service. If you don&apos;t agree,
            don&apos;t use the Service.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-brand-dark">2. What the Service is</h2>
          <p>
            The Service generates strength and conditioning training programs for ultimate frisbee players using
            an AI system, reviewed and approved by a human coach before being delivered to you. Programs are based
            on information you provide (intake answers, logged workouts, injury history) and are not a substitute
            for individualized medical or professional athletic training advice.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-brand-dark">3. Not medical advice — health &amp; safety</h2>
          <p>
            <strong>The Service is not a medical service, and nothing in it constitutes medical advice, diagnosis,
            or treatment.</strong> Consult a physician before beginning any new exercise program, especially if you
            have a pre-existing injury, medical condition, or are unsure whether an activity is appropriate for
            you. You are solely responsible for stopping any exercise that causes pain and for seeking appropriate
            medical care.
          </p>
          <p>
            Exercise carries an inherent risk of injury. By using the Service, you voluntarily assume all risks
            associated with performing the programs it generates, including but not limited to injury, disability,
            or death. To the fullest extent permitted by law, Quinn Ledak is not liable for any injury arising
            from your use of a program generated by the Service.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-brand-dark">4. Accounts &amp; eligibility</h2>
          <p>
            You must provide accurate information, including accurate injury and health history — the programs
            you receive are only as safe as the information you give us. You must be at least 18 years old to
            create an account. You are responsible for keeping your login credentials confidential and for all
            activity under your account.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-brand-dark">5. Cost during the beta</h2>
          <p>
            The Service is currently offered free of charge as part of an early beta. If that changes in the
            future, we&apos;ll notify you before any fees apply to your account, and these Terms will be updated
            with the actual pricing, billing cadence, and cancellation terms at that time.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-brand-dark">6. Your content</h2>
          <p>
            You retain ownership of the information you provide (intake answers, logged workouts, notes). You
            grant us a license to use it to operate the Service — including generating your programs and, if you
            or your coach opt in, using an anonymized/de-identified version of an approved program as a reference
            example to help generate other athletes&apos; programs.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-brand-dark">7. Termination</h2>
          <p>
            You may stop using the Service and request account deletion at any time. We may suspend or terminate
            an account that violates these Terms or misuses the Service (including attempting to abuse or overload
            the AI generation features).
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-brand-dark">8. Disclaimer of warranties</h2>
          <p>
            The Service is provided &ldquo;as is&rdquo; without warranties of any kind, express or implied,
            including fitness for a particular purpose. We do not guarantee that AI-generated content will be
            error-free or achieve any particular athletic outcome. As an early beta, the Service may change,
            break, or be discontinued with little notice.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-brand-dark">9. Limitation of liability</h2>
          <p>
            To the fullest extent permitted by law, Quinn Ledak will not be liable for any indirect, incidental,
            or consequential damages arising from your use of the Service. Because the Service is currently free,
            our total liability for any claim will not exceed $100.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-brand-dark">10. Changes to these terms</h2>
          <p>
            We may update these Terms from time to time. We&apos;ll notify you of material changes (e.g. by email
            or in-app notice) before they take effect.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-brand-dark">11. Governing law &amp; contact</h2>
          <p>
            These Terms are governed by the laws of the State of Vermont. Questions? Contact us at{" "}
            <a href="mailto:qledak@gmail.com" className="text-brand underline">
              qledak@gmail.com
            </a>
            .
          </p>
        </section>
      </div>
    </main>
  );
}
